# Generated by Django 5.1.1 on 2024-09-21 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_suppliers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_suppliers', to='products.product', verbose_name='Product')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_products', to='products.suppliers', verbose_name='Supplier')),
            ],
            options={
                'verbose_name': 'Product Supplier',
                'verbose_name_plural': 'Product Suppliers',
                'ordering': ['product'],
            },
        ),
    ]
